// Package openapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.8.2 DO NOT EDIT.
package openapi

import (
	"time"
)

// 共通レスポンスヘッダ
type CommonHeader struct {
	// エラー内容
	ErrorMessage string `json:"error_message"`

	// ステータスコード
	Status string `json:"status"`
}

// 共通レスポンス
type CommonResult struct {
	// 共通レスポンスヘッダ
	Header CommonHeader `json:"header"`

	// レスポンス部（Null）
	Response []interface{} `json:"response"`
}

// エラー情報
type Error struct {
	// エラー内容
	Detail string `json:"detail"`

	// ステータスコード
	StatusCode string `json:"statusCode"`
}

// マイ店舗操作インターフェース
type RequestMyShopParams struct {
	// 会員ID
	EmpNo string `json:"emp_no"`

	// 店舗コード
	ShopList []string `json:"shop_list"`
}

// 会員情報更新
type RequestUserUpdateParams struct {
	// 会員ID
	EmpNo string `json:"emp_no"`

	// 更新項目一覧
	UserData struct {
		// 生年月日。フォーマットは"2000-01-01"
		BirthDate time.Time `json:"birth_date"`

		// 名前
		FirstName string `json:"first_name"`

		// 性別
		Gender string `json:"gender"`

		// 名字
		LastName string `json:"last_name"`

		// 更新日
		UpdatedAt *time.Time `json:"updated_at,omitempty"`
	} `json:"user_data"`
}

// 失敗
type ResultError struct {
	// エラー情報
	Error Error `json:"error"`

	// 結果
	Result bool `json:"result"`
}

// マイ店舗一覧結果
type ResultMyShop struct {
	// 共通レスポンスヘッダ
	Header CommonHeader `json:"header"`

	// レスポンス部
	Response []ShopList `json:"response"`
}

// 成功
type ResultOK struct {
	// 結果
	Result bool `json:"result"`
}

// ユーザ詳細レスポンス
type ResultUserDetail struct {
	// 共通レスポンスヘッダ
	Header CommonHeader `json:"header"`

	// 会員情報詳細構造体
	Response UserData `json:"response"`
}

// 店舗ID配列
type ShopList struct {
	// 店舗名
	Name string `json:"name"`

	// 店舗コード
	ShopCd string `json:"shop_cd"`
}

// 会員情報詳細構造体
type UserData struct {
	// 生年月日
	BirthDate string `json:"birth_date"`

	// 作成日。フォーマットは"2000-01-01T00:00:00Z"
	CreatedAt time.Time `json:"created_at"`

	// 会員ID
	EmpNo string `json:"emp_no"`

	// 名前
	FirstName string `json:"first_name"`

	// 性別
	Gender string `json:"gender"`

	// 名字
	LastName string `json:"last_name"`

	// 更新日。フォーマットは"2000-01-01T00:00:00Z"
	UpdatedAt time.Time `json:"updated_at"`
}

// GetMyEmpNo defines model for getMyEmpNo.
type GetMyEmpNo string

// PostApiV2MyshopJSONBody defines parameters for PostApiV2Myshop.
type PostApiV2MyshopJSONBody RequestMyShopParams

// PostApiV2MyshopDeleteJSONBody defines parameters for PostApiV2MyshopDelete.
type PostApiV2MyshopDeleteJSONBody RequestMyShopParams

// PostApiV2UserUpdateJSONBody defines parameters for PostApiV2UserUpdate.
type PostApiV2UserUpdateJSONBody RequestUserUpdateParams

// PostApiV2MyshopJSONRequestBody defines body for PostApiV2Myshop for application/json ContentType.
type PostApiV2MyshopJSONRequestBody PostApiV2MyshopJSONBody

// PostApiV2MyshopDeleteJSONRequestBody defines body for PostApiV2MyshopDelete for application/json ContentType.
type PostApiV2MyshopDeleteJSONRequestBody PostApiV2MyshopDeleteJSONBody

// PostApiV2UserUpdateJSONRequestBody defines body for PostApiV2UserUpdate for application/json ContentType.
type PostApiV2UserUpdateJSONRequestBody PostApiV2UserUpdateJSONBody

