openapi: 3.0.0
tags: [ ]
info:
  title: go-echo-sample-api
  version: '0.9'
  description: Echoサンプル
  contact:
    name: k-sato
    url: 'https://tribeat.com'
    email: info@tribeat.com

paths:
  /api/open/healthcheck:
    get:
      summary: ヘルスチェック
      tags: [ "システム" ]
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/resultOK'
              example:
                result: true
        '500':
          description: NG
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/resultError'



  /api/v2/user/detail/{memberId}:
    get:
      summary: 会員情報 参照
      tags: [ "会員管理" ]
      parameters:
        - $ref: '#/components/parameters/getMyMemberId'
      responses:
        '200':
          description: 会員情報の取得
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/resultUserDetail'

        '400':
          description: NG
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/commonResult'
              examples:
                sample-1:
                  summary: Error
                  value:
                    header:
                      status: "400"
                      error_message: "リクエストパラメータ不正"
                    response: { }
        '401':
          description: API-Gatewayレスポンス
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/commonResult'
              examples:
                sample-1:
                  summary: Error
                  value:
                    header:
                      status: "401"
                      error_message: "Unauthorized"
                    response: [ ]

        '500':
          description: NG
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/commonResult'
              examples:
                sample-1:
                  summary: Error
                  value:
                    header:
                      status: "500"
                      error_message: "予期せぬエラーが発生"
                    response: null

  /api/v2/user/update:
    post:
      summary: 会員情報 変更
      tags: [ "会員管理" ]
      requestBody:
        description: 会員情報 変更リクエスト
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/requestUserUpdateParams'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/commonResult'
              examples:
                sample-1:
                  summary: OK
                  value:
                    header:
                      status: "200"
                      error_message: ""
                    response: { }
        '400':
          description: NG
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/commonResult'
              examples:
                sample-1:
                  summary: Error
                  value:
                    header:
                      status: "400"
                      error_message: "リクエストパラメータ不正"
                    response: null
        '401':
          description: API-Gatewayレスポンス
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/commonResult'
              examples:
                sample-1:
                  summary: Error
                  value:
                    header:
                      status: "401"
                      error_message: "Unauthorized"
                    response: [ ]
        '500':
          description: NG
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/commonResult'
              examples:
                sample-1:
                  summary: Error
                  value:
                    header:
                      status: "500"
                      error_message: "予期せぬエラーが発生"
                    response: null

  /api/v2/myshop/{memberId}:
    get:
      summary: マイ店舗 一覧取得
      tags: [ "マイ店舗" ]
      parameters:
        - $ref: '#/components/parameters/getMyMemberId'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/resultMyShop'

        '401':
          description: API-Gatewayレスポンス
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/commonResult'
              examples:
                sample-1:
                  summary: Error
                  value:
                    header:
                      status: "401"
                      error_message: "Unauthorized"
                    response: [ ]
        '500':
          description: NG
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/commonResult'
              examples:
                sample-1:
                  summary: Error
                  value:
                    header:
                      status: "500"
                      error_message: "予期せぬエラーが発生"
                    response: [ ]

  /api/v2/myshop:
    post:
      summary: マイ店舗 登録
      tags: [ "マイ店舗" ]
      requestBody:
        description: マイ店舗登録リクエスト
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/requestMyShopParams'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/resultMyShop'
        '400':
          description: NG
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/commonResult'
              examples:
                sample-1:
                  summary: Error
                  value:
                    header:
                      status: "400"
                      error_message: "リクエストパラメータ不正"
                    response: [ ]
        '401':
          description: API-Gatewayレスポンス
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/commonResult'
              examples:
                sample-1:
                  summary: Error
                  value:
                    header:
                      status: "401"
                      error_message: "Unauthorized"
                    response: [ ]
        '500':
          description: NG
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/commonResult'
              examples:
                sample-1:
                  summary: Error
                  value:
                    header:
                      status: "500"
                      error_message: "予期せぬエラーが発生"
                    response: [ ]
  /api/v2/myshop/delete:
    post:
      summary: マイ店舗削除
      tags: [ "マイ店舗" ]
      requestBody:
        description: マイ店舗削除リクエスト
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/requestMyShopParams'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/resultMyShop'
        '400':
          description: NG
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/commonResult'
              examples:
                sample-1:
                  summary: Error
                  value:
                    header:
                      status: "400"
                      error_message: "リクエストパラメータ不正"
                    response: [ ]
        '401':
          description: API-Gatewayレスポンス
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/commonResult'
              examples:
                sample-1:
                  summary: Error
                  value:
                    header:
                      status: "401"
                      error_message: "Unauthorized"
                    response: [ ]
        '500':
          description: NG
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/commonResult'
              examples:
                sample-1:
                  summary: Error
                  value:
                    header:
                      status: "500"
                      error_message: "予期せぬエラーが発生"
                    response: [ ]


components:
  parameters:
    getMyMemberId:
      name: memberId
      in: path
      description: 取得対象memberId
      required: true
      schema:
        type: string
        minLength: 1

  schemas:
    resultOK:
      type: object
      description: 成功
      properties:
        result:
          type: boolean
          description: 結果
      required:
        - result
    resultError:
      type: object
      description: 失敗
      properties:
        result:
          type: boolean
          description: 結果
        error:
          $ref: '#/components/schemas/error'
      required:
        - result
        - error
        
    error:
      type: object
      description: エラー情報
      properties:
        statusCode:
          type: string
          description: ステータスコード
        detail:
          type: string
          description: エラー内容
      required:
        - statusCode
        - detail

    commonHeader:
      type: object
      description: 共通レスポンスヘッダ
      properties:
        status:
          type: string
          description: ステータスコード
        error_message:
          type: string
          default: ""
          description: エラー内容
      required:
        - status
        - error_message
    commonResult:
      type: object
      description: 共通レスポンス
      properties:
        header:
          $ref: '#/components/schemas/commonHeader'
        response:
          type: array
          description: レスポンス部（Null）
          items:
            default: { }
      required:
        - header
        - response


    requestMyShopParams:
      type: object
      description: マイ店舗操作インターフェース
      properties:
        member_id:
          type: string
          description: 会員ID
          minLength: 1
        shop_list:
          type: array
          description: 店舗コード
          items:
            type: string

      required:
        - member_id
        - shop_list

    resultMyShop:
      type: object
      description: マイ店舗一覧結果
      properties:
        header:
          $ref: '#/components/schemas/commonHeader'
        response:
          type: array
          description: レスポンス部
          items:
            $ref: '#/components/schemas/shopList'
      required:
        - header
        - response

    shopList:
      type: object
      description: 店舗ID配列
      properties:
        shop_cd:
          type: string
          description: 店舗コード
        name:
          type: string
          description: 店舗名

      required:
        - shop_cd
        - name


    requestUserUpdateParams:
      type: object
      description: 会員情報更新
      properties:
        member_id:
          type: string
          description: 会員ID
          minLength: 1
        user_data:
          type: object
          description: 更新項目一覧
          items:
            $ref: '#/components/schemas/userUpdateParam'
      required:
        - member_id
        - user_data

    userUpdateParam:
      type: object
      description: 会員情報詳細構造体
      properties:
        birth_date:
          description: 生年月日。フォーマットは"2000-01-01T00:00:00Z"
          type: string
          format: 'date-time'
        first_name: 
          description: 名前 
          type: string
          default: ""
        last_name: 
          description: 名字 
          type: string
          default: ""          
        gender:
          description: 性別
          type: string
        updated_at:
          description: 更新日。フォーマットは"2000-01-01T00:00:00Z"
          type: string
          format: 'date-time'
        created_at:
          description: 作成日。フォーマットは"2000-01-01T00:00:00Z"
          type: string
          format: 'date-time'
      required:
        - birth_date
        - first_name
        - last_name
        - gender
        - updated_at
        - created_at



    resultUserDetail:
      type: object
      description: ユーザ詳細レスポンス
      properties:
        header:
          $ref: '#/components/schemas/commonHeader'
        response:
          $ref: '#/components/schemas/userData'
      required:
        - header
        - response

    userData:
      type: object
      description: 会員情報詳細構造体
      properties:
        emp_no:
          description: 会員ID
          type: string
        birth_date:
          description: 生年月日。フォーマットは"2000-01-01T00:00:00Z"
          type: string
          format: 'date-time'
        first_name: 
          description: 名前 
          type: string
          default: ""
        last_name: 
          description: 名字 
          type: string
          default: ""          
        gender:
          description: 性別
          type: string
        updated_at:
          description: 更新日。フォーマットは"2000-01-01T00:00:00Z"
          type: string
          format: 'date-time'
        created_at:
          description: 作成日。フォーマットは"2000-01-01T00:00:00Z"
          type: string
          format: 'date-time'
      required:
        - emp_no
        - birth_date
        - first_name
        - last_name
        - gender
        - updated_at
        - created_at


